### ISSUE TITLE
Video of Part 2 is invalid.

### ISSUE THREAD

**Issue by Yan9564** [bguedj/icml2019#1]
Dear Professor Guedj,

I hope this message finds you well. I am writing to kindly request your assistance with accessing the Part 2 video on Facebook research. Unfortunately, the current link seems to be invalid. I understand that you have a busy schedule, but if it is not too much trouble, could you please update the link or provide an alternative method to access the video?

Best regards,
Bingxin

**Comment by bguedj** [comment]
Dear Bingxin,
Thanks for reaching out. Part 2 seems fine but surely you mean Part 1? I'm afraid this depends on ICML 2019 and I have no control over their facebook page, and this is the only link to that video that I am aware of. You can find videos of some of my other talks (which have a strong overlap with this tutorial) on my website https://bguedj.github.io/talks/ or on my YouTube channel https://www.youtube.com/channel/UCkp0b5jlZoIc4U-sDav4Fuw
Hope this helps!
Benjamin

**Comment by Yan9564** [comment]
Yes, it should be Part 1, thank you so much!
